# The Site Configuration
theme: jekyll-theme-chirpy
lang: en
timezone: America/Puerto_Rico

# --- Identity / SEO ---
title: Gustavo Bertran, Master's Student
tagline: UPRM Biology
description: >-
  A website encompassing all past, current and future works

# Use your GitHub Pages URL (no trailing slash)
# Example: https://USERNAME.github.io
url: "https://gustavobertran.github.io"
baseurl: ""  # keep empty for user/ORG pages

github:
  username: GustavoBertran

twitter:
  username: @GustiBertran  # or leave blank/remove

social:
  name: Gustavo Bertran
  email: YOUREMAIL@example.com
  links:
    - https://twitter.com/GustiBertran
    - https://github.com/GustavoBertran
    # - https://www.linkedin.com/in/YOUR_ID

# Optional verifications (leave blank if you’re not using)
webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:
  baidu:
  facebook:

# --- Analytics (optional; pick ONE you use) ---
analytics:
  google:
    id: ""     # e.g., G-XXXXXXXXXX
  goatcounter:
    id:
  umami:
    id:
    domain:
  matomo:
    id:
    domain:
  cloudflare:
    id:
  fathom:
    id:

pageviews:
  provider:

# --- Look & feel ---
theme_mode:       dark # [light | dark] (empty = system default)
cdn:
avatar: /assets/Profile_Pic.jpg  # put an image there or leave blank
social_preview_image:            # e.g., /assets/img/og-cover.png
toc: true

comments:
  provider:       # [disqus | utterances | giscus]
  disqus:
    shortname:
  utterances:
    repo:
    issue_term:
  giscus:
    repo:
    repo_id:
    category:
    category_id:
    mapping:
    strict:
    input_position:
    lang:
    reactions_enabled:

assets:
  self_host:
    enabled:
    env:

pwa:
  enabled: true
  cache:
    enabled: true
    deny_paths:

paginate: 10

# ------------ The following options are fine to keep as default ------------------
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

